/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.calculator;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author 92016648
 */
public class JCalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form JCalculaterFrame
     */
    public JCalculatorFrame() {
        initComponents();
        setTitle("Calculator");
    }
   Calculatorclass cc = new Calculatorclass();
    String operand="";
    
    public void getOperand(javax.swing.JButton button){
        operand+=button.getText();
        cc.setOperand(operand);
        txtDisplay.setText(operand);
    }
      private void getOperator(int opt){
        cc.setOperator(opt);
        operand="";
    }
    private void process(){
        DecimalFormat df = new DecimalFormat("######,###.###############");
        cc.process();
        operand = "";
        txtDisplay.setText(df.format(cc.getResult())+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        msgMessage = new javax.swing.JOptionPane();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        panelBase = new javax.swing.JPanel();
        btnEqual = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btn1byX = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnPow = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPosNeg = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        panelEx = new javax.swing.JPanel();
        rdbDegree = new javax.swing.JRadioButton();
        rdbRadians = new javax.swing.JRadioButton();
        btnasin = new javax.swing.JButton();
        btnacos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnAtan = new javax.swing.JButton();
        btnPI = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        rdbBasic = new javax.swing.JRadioButtonMenuItem();
        rdbExtends = new javax.swing.JRadioButtonMenuItem();
        mnuFont = new javax.swing.JMenu();
        rdbPlain = new javax.swing.JRadioButtonMenuItem();
        rdbBold = new javax.swing.JRadioButtonMenuItem();
        mnuRound = new javax.swing.JMenu();
        rdb1 = new javax.swing.JRadioButtonMenuItem();
        rdb2 = new javax.swing.JRadioButtonMenuItem();
        rdb3 = new javax.swing.JRadioButtonMenuItem();
        rdb4 = new javax.swing.JRadioButtonMenuItem();
        rdb5 = new javax.swing.JRadioButtonMenuItem();
        rdb6 = new javax.swing.JRadioButtonMenuItem();
        rdb7 = new javax.swing.JRadioButtonMenuItem();
        rdb8 = new javax.swing.JRadioButtonMenuItem();
        rdb9 = new javax.swing.JRadioButtonMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();
        mnuHotKey = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 450));

        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnPoint.setText(".");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnCA.setText("CA");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });

        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btn1byX.setText("1/x");
        btn1byX.setAlignmentX(5.0F);
        btn1byX.setAlignmentY(5.0F);
        btn1byX.setMaximumSize(new java.awt.Dimension(39, 23));
        btn1byX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1byXActionPerformed(evt);
            }
        });

        btnX.setText("x!");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnSub.setText("-");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.setPreferredSize(new java.awt.Dimension(7, 23));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnPow.setText("x^y");
        btnPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnPosNeg.setText("+/-");
        btnPosNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosNegActionPerformed(evt);
            }
        });

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbDegree);
        rdbDegree.setSelected(true);
        rdbDegree.setText("Degree");

        buttonGroup2.add(rdbRadians);
        rdbRadians.setText("Radians");

        btnasin.setText("asin");
        btnasin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasinActionPerformed(evt);
            }
        });

        btnacos.setText("acos");
        btnacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacosActionPerformed(evt);
            }
        });

        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnAtan.setText("atan");
        btnAtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtanActionPerformed(evt);
            }
        });

        btnPI.setText("PI");
        btnPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExLayout = new javax.swing.GroupLayout(panelEx);
        panelEx.setLayout(panelExLayout);
        panelExLayout.setHorizontalGroup(
            panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExLayout.createSequentialGroup()
                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExLayout.createSequentialGroup()
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnasin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExLayout.createSequentialGroup()
                        .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelExLayout.createSequentialGroup()
                                .addComponent(rdbDegree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbRadians))
                            .addGroup(panelExLayout.createSequentialGroup()
                                .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnacos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelExLayout.createSequentialGroup()
                                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPI, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelExLayout.setVerticalGroup(
            panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbDegree)
                    .addComponent(rdbRadians))
                .addGap(24, 24, 24)
                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnasin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnacos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(panelEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBaseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBaseLayout.createSequentialGroup()
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelBaseLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn1byX, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPow, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelBaseLayout.createSequentialGroup()
                            .addComponent(btnCA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(213, Short.MAX_VALUE)))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBaseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBaseLayout.createSequentialGroup()
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBaseLayout.createSequentialGroup()
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBaseLayout.createSequentialGroup()
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn1byX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        jMenu1.setText("File");

        rdbBasic.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        buttonGroup1.add(rdbBasic);
        rdbBasic.setMnemonic('B');
        rdbBasic.setSelected(true);
        rdbBasic.setText("Basic");
        rdbBasic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbBasicItemStateChanged(evt);
            }
        });
        rdbBasic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rdbBasicKeyPressed(evt);
            }
        });
        jMenu1.add(rdbBasic);

        rdbExtends.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        buttonGroup1.add(rdbExtends);
        rdbExtends.setMnemonic('E');
        rdbExtends.setText("Extended");
        rdbExtends.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbExtendsItemStateChanged(evt);
            }
        });
        rdbExtends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbExtendsActionPerformed(evt);
            }
        });
        jMenu1.add(rdbExtends);

        jMenuBar1.add(jMenu1);

        mnuFont.setText("Font");

        rdbPlain.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup3.add(rdbPlain);
        rdbPlain.setSelected(true);
        rdbPlain.setText("Plain");
        rdbPlain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbPlainItemStateChanged(evt);
            }
        });
        mnuFont.add(rdbPlain);

        rdbBold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup3.add(rdbBold);
        rdbBold.setText("Bold");
        rdbBold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbBoldItemStateChanged(evt);
            }
        });
        mnuFont.add(rdbBold);

        jMenuBar1.add(mnuFont);

        mnuRound.setText("Round");

        buttonGroup4.add(rdb1);
        rdb1.setText("1");
        rdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1ActionPerformed(evt);
            }
        });
        mnuRound.add(rdb1);

        buttonGroup4.add(rdb2);
        rdb2.setText("2");
        mnuRound.add(rdb2);

        buttonGroup4.add(rdb3);
        rdb3.setText("3");
        mnuRound.add(rdb3);

        buttonGroup4.add(rdb4);
        rdb4.setText("4");
        mnuRound.add(rdb4);

        buttonGroup4.add(rdb5);
        rdb5.setText("5");
        mnuRound.add(rdb5);

        buttonGroup4.add(rdb6);
        rdb6.setText("6");
        mnuRound.add(rdb6);

        buttonGroup4.add(rdb7);
        rdb7.setText("7");
        rdb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb7ActionPerformed(evt);
            }
        });
        mnuRound.add(rdb7);

        buttonGroup4.add(rdb8);
        rdb8.setText("8");
        mnuRound.add(rdb8);

        buttonGroup4.add(rdb9);
        rdb9.setText("9");
        mnuRound.add(rdb9);

        jMenuBar1.add(mnuRound);

        mnuHelp.setText("Help");

        mnuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        mnuAbout.setMnemonic('A');
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        mnuHotKey.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, 0));
        mnuHotKey.setMnemonic('K');
        mnuHotKey.setText("Hot Key ");
        mnuHotKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHotKeyActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHotKey);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb7ActionPerformed

    private void rdbExtendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbExtendsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbExtendsActionPerformed

    private void rdbBasicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbBasicItemStateChanged
        // TODO add your handling code here:
         this.setSize(350, 550);
        if(panelBase.isVisible())
        {
            panelEx.setVisible(false);
            panelEx.setEnabled(false); 
        }else
        {
            panelBase.setVisible(true); 
        }
  
    }//GEN-LAST:event_rdbBasicItemStateChanged

    private void rdbExtendsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbExtendsItemStateChanged
        // TODO add your handling code here:
        this.setSize(550, 450);
        if (panelEx.isVisible())
        {
            panelEx.setVisible(false);
        }else
        {
            panelEx.setVisible(true); 
        }
    }//GEN-LAST:event_rdbExtendsItemStateChanged

    private void rdbPlainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbPlainItemStateChanged
        // TODO add your handling code here:
        if(rdbPlain.isSelected())
        {
            txtDisplay.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
           
            
        }
    }//GEN-LAST:event_rdbPlainItemStateChanged

    private void rdbBoldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbBoldItemStateChanged
        // TODO add your handling code here:
        txtDisplay.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14)); 
    }//GEN-LAST:event_rdbBoldItemStateChanged

    private void rdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1ActionPerformed
        // TODO add your handling code here:
            DecimalFormat df = new DecimalFormat("##,###.#");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
    }//GEN-LAST:event_rdb1ActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
        msgMessage.showMessageDialog(this, "Calculater\n Created by: Computer power plus student","ABout", javax.swing.JOptionPane.INFORMATION_MESSAGE); 
       
    }//GEN-LAST:event_mnuAboutActionPerformed

    private void mnuHotKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHotKeyActionPerformed
        // TODO add your handling code here:
         msgMessage.showMessageDialog(this, "A- About\n  k-HotKey\n Ctrl+p- Plain Font\n Ctrl+B- Bold Font\n B- Basic View\n E-Extended veiw\n Alt+p -PI\n Alt+E- E ",
                "Hotkey", javax.swing.JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_mnuHotKeyActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        getOperand(btn1); 
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here: 
         getOperand(btn2); 
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
         getOperand(btn3); 
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
         getOperand(btn4); 
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
         getOperand(btn5); 
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
         getOperand(btn6); 
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
         getOperand(btn7); 
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
         getOperand(btn8); 
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
         getOperand(btn9); 
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
         getOperand(btn0); 
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        // TODO add your handling code here:
         getOperand(btnPoint); 
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        process();
        DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
        
        
            
        
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        // TODO add your handling code here:
          getOperator(2); 
        txtDisplay.setText("");
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        // TODO add your handling code here:
          getOperator(3); 
        txtDisplay.setText("");   
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
         
            getOperator(4); 
        txtDisplay.setText("");
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         getOperator(1); 
        txtDisplay.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btn1byXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1byXActionPerformed
        // TODO add your handling code here:    
       double a = Double.parseDouble(String.valueOf(txtDisplay.getText()));
        if(a == 0){
            JOptionPane.showMessageDialog(this, "Cannot divide by zero.", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else{
        getOperator(6); 
        process();
        }
       
    }//GEN-LAST:event_btn1byXActionPerformed

    private void btnPosNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosNegActionPerformed
        // TODO add your handling code here:
           getOperator(5); 
        process();
    }//GEN-LAST:event_btnPosNegActionPerformed

    private void btnPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowActionPerformed
        // TODO add your handling code here:
          getOperator(7);  
    }//GEN-LAST:event_btnPowActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
     double x = Double.parseDouble(String.valueOf(txtDisplay.getText()));
        if(x<0 || x>20 || x == 1.0){
            JOptionPane.showMessageDialog(this, "Must be positive integer between 0 and 20", "ERROR Message", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else{
        getOperator(8);
        process();
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnXActionPerformed

    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
        // TODO add your handling code here:
         cc.reset();
        txtDisplay.setText("");
    }//GEN-LAST:event_btnCAActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
        
          if(operand.length()>1){
            operand = operand.substring(0, operand.length()-1);
            cc.setOperand(operand);
            txtDisplay.setText(operand);
        }else{
            operand = "";
            cc.setOperand(operand);
            txtDisplay.setText("");
        } 
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // TODO add your handling code here:
         int Sin = 1;

        if(Sin>0){
        
            if(rdbDegree.isSelected()){
              
                getOperator(9);
                process();
            }else{
                getOperator(10);
                process();
            }
             
        
        }
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnasinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasinActionPerformed
        // TODO add your handling code here:
           int asin = 1;

        if(asin>0){

            if(rdbDegree.isSelected()){

                getOperator(11);
                process();
            }else{
                getOperator(12);
                process();
            }
               
        }
    }//GEN-LAST:event_btnasinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here:
         int cos = 1;

        if(cos>0){

            if(rdbDegree.isSelected()){

                getOperator(13);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }else{
                getOperator(14);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }
      
        }
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacosActionPerformed
        // TODO add your handling code here:
        int acos = 1;

        if(acos>0){

            if(rdbDegree.isSelected()){

                getOperator(15);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }else{
                getOperator(16);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }
       
        }
    }//GEN-LAST:event_btnacosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // TODO add your handling code here:
         int Tan= 1;

        if(Tan>0){

            if(rdbDegree.isSelected()){

                getOperator(17);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }else{
                getOperator(18);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }
       
        }
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnAtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtanActionPerformed
        // TODO add your handling code here:
         int Atan = 1;

        if(Atan>0){

            if(rdbDegree.isSelected()){

                getOperator(19);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }else{
                getOperator(20);
                process();
                DecimalFormat df = new DecimalFormat("##,###.##");
        txtDisplay.setText(df.format(Double.valueOf(txtDisplay.getText()))+"");
            }
       
       
        }
    }//GEN-LAST:event_btnAtanActionPerformed

    private void btnPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIActionPerformed
        // TODO add your handling code here:


        getOperator(21);
        process();
        
        int firstDouble=0;
        int secondDouble=0;
          
    }//GEN-LAST:event_btnPIActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:


        getOperator(22);
        process();
        
      int   firstDouble=0;
        int secondDouble=0;
    }//GEN-LAST:event_btnEActionPerformed

    private void rdbBasicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdbBasicKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbBasicKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1byX;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAtan;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnPosNeg;
    private javax.swing.JButton btnPow;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnacos;
    private javax.swing.JButton btnasin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuFont;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHotKey;
    private javax.swing.JMenu mnuRound;
    private javax.swing.JOptionPane msgMessage;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelEx;
    private javax.swing.JRadioButtonMenuItem rdb1;
    private javax.swing.JRadioButtonMenuItem rdb2;
    private javax.swing.JRadioButtonMenuItem rdb3;
    private javax.swing.JRadioButtonMenuItem rdb4;
    private javax.swing.JRadioButtonMenuItem rdb5;
    private javax.swing.JRadioButtonMenuItem rdb6;
    private javax.swing.JRadioButtonMenuItem rdb7;
    private javax.swing.JRadioButtonMenuItem rdb8;
    private javax.swing.JRadioButtonMenuItem rdb9;
    private javax.swing.JRadioButtonMenuItem rdbBasic;
    private javax.swing.JRadioButtonMenuItem rdbBold;
    private javax.swing.JRadioButton rdbDegree;
    private javax.swing.JRadioButtonMenuItem rdbExtends;
    private javax.swing.JRadioButtonMenuItem rdbPlain;
    private javax.swing.JRadioButton rdbRadians;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
